on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Suapp
    steps:
      - name: Install suave-geth
        uses: ferranbt/flashbots-toolchain@v0.2

      - name: Which suave-geth
        run: suave-geth version
