on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Suapp
    steps:
      - name: Install suave-geth
        uses: ferranbt/flashbots-toolchain@v0.3
        with:
          builder-playground: latest

      - name: Which suave-geth
        run: suave-geth version
