on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Suapp
    steps:
      - name: Install stuff
        uses: ferranbt/flashbots-toolchain@v0.5
        with:
          suave-geth: latest
          builder-playground: latest

      - name: Which suave-geth
        run: suave-geth version

      - name: Which 2
        run: which suave-geth

      - name: Which builder playground
        run: which builder-playground

      - name: Run builder playground
        run: docker compose

      - name: Run other docker-compose
        run: docker-compose
